name: Actions Workflow

on:
    push:
        branches:
          - master
        # branches-ignore: -run on all except :

        tags:
            - v1.*
        # paths:         -> run only when .js file is changed
        #    - "**.js"
        #    - "!filename.js" ingore changes from this file

   # schedule        -> run worckflow every 5 min (minim)
   # pull_request
   # repository_dispatch -> external trigger

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: |
                  pwd
                  ls
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_WORKSPACE
                # echo ${{ github.token }}
            - name: Checkout
              uses: actions/checkout@v1
            - name: List files
              run: |
                  pwd
                  ls -la
            - name: Simple JS Actions
              id: greet
              uses: actions/hello-world-javascript-action@v1
              with: 
                  who-to-greet: John
            - name: Log Greeting time
              run: echo "${{ steps.greet.outputs.time}}"