name: Shell Commands

on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "step 1"
            - name: multiline script
              run: |
                  node -v
                  npm -v